### ISSUE TITLE
Server response: You do not own this addon. (status: 403) FAIL error when trying to sign

### ISSUE THREAD

**Issue by dma156** [Nerixyz/ttv-tools#2]
Sorry if I'm not seeing the obvious solution but basically getting this error, set the environment variables with my API credentials and getting the following. Logs:

```
PS D:\Daniel\Desktop\ttv-tools-master> npm link tslib
D:\Daniel\Desktop\ttv-tools-master\node_modules\tslib -> C:\Users\Daniel\AppData\Roaming\npm\node_modules\tslib
PS D:\Daniel\Desktop\ttv-tools-master> npm run build

> ttv-adblock@1.0.0 build D:\Daniel\Desktop\ttv-tools-master
> rollup -c -m && npm run copy-videos && web-ext build -s dist/build -o -a dist


src/background/background.ts, src/content-script.ts → dist/build...
created dist/build in 1.8s

src/context/context-script.ts → dist/build...
created dist/build in 1s

src/options/options.ts → dist/build/options...
created dist/build/options in 884ms

> ttv-adblock@1.0.0 copy-videos D:\Daniel\Desktop\ttv-tools-master
> copyfiles videos/**/* dist/build

Applying config file: .\package.json
Building web extension from D:\Daniel\Desktop\ttv-tools-master\dist\build
Destination exists, overwriting: dist\ttv-tools-0.3.0.zip
Your web extension is ready: dist\ttv-tools-0.3.0.zip
PS D:\Daniel\Desktop\ttv-tools-master> npm run sign

> ttv-adblock@1.0.0 sign D:\Daniel\Desktop\ttv-tools-master
> web-ext sign -s dist/build -a dist

Applying config file: .\package.json
Building web extension from D:\Daniel\Desktop\ttv-tools-master\dist\build
Server response: You do not own this addon. (status: 403)
FAIL

o: The extension could not be signed
    at D:\Daniel\Desktop\ttv-tools-master\node_modules\web-ext\dist\web-ext.js:1:69703
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at A.execute (D:\Daniel\Desktop\ttv-tools-master\node_modules\web-ext\dist\web-ext.js:1:34478)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ttv-adblock@1.0.0 sign: `web-ext sign -s dist/build -a dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ttv-adblock@1.0.0 sign script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Daniel\AppData\Roaming\npm-cache\_logs\2021-01-16T01_50_19_529Z-debug.log
```

**Comment by Nerixyz** [comment]
It's probably because of [this](https://github.com/Nerixyz/ttv-tools/blob/master/manifest.json#L42) line. Have you tried changing it?

**Comment by dma156** [comment]
Ah okay, no, what do I change that to?

**Comment by Jar121** [comment]
I'm also wondering what to change this to, any help would be greatly appreciated!

**Comment by Nerixyz** [comment]
You can now download the addon from GitHub [here](https://github.com/Nerixyz/ttv-tools/releases).
